spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.130.102:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    application:
        name: gulimall-product

mybatis-plus:
    #classpath*表示不止扫描,还扫描引入的其他jar包的类路径
    mapperLocations: classpath*:mapper/**/*.xml
    global-config:
        db-config:
            id-type: auto



server:
    port: 10000