spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
        #MySQL\u914D\u7F6E
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.130.102:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root

mybatis-plus:
    #classpath\u8868\u793A\u53EA\u626B\u63CF\u81EA\u5DF1\u9879\u76EE\u4E0B\u7684  classpath*\u8868\u793A\u4E0D\u4EC5\u626B\u63CF\u81EA\u5DF1\u9879\u76EE\u7684\u7684xml\u8FD8\u626B\u63CF\u5E94\u7528\u7684\u5176\u4ED6jar\u5305\u4E2D\u7684xml
    mapperLocations: classpath*:mapper/**/*.xml
    #\u8BBE\u7F6E\u4E3B\u952E\u81EA\u589E
    global-config:
        db-config:
            id-type: auto



server:
    port: 10000